service: ether

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 1024
  timeout: 60
  stage: hls
  region: us-east-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::*"
             - "/*"


package:
 exclude:
   - ./**
 include:
   - ./bin/**
   - ./lib/**

functions:
  multirate-transcoder:
    handler: bin/hls-multirate-transcoder

